### ISSUE TITLE
authetic theme does not jump top URL#something

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#1005]
Hi Ilia, while developing the software module for synology I discovered that authetic ignores the given #anchor from URL, example:

If you klick on a categorie in the Software tree you will be redirected to something like this:
.../software/tree.cgi#Productivity/Spreadsheets?xnavigation=1

In grey framed theme the content the frame scroll to Spreadsheets, in authentic the top of the list is displayed.

![image](https://user-images.githubusercontent.com/4593242/35700436-44a51a7c-0793-11e8-811b-937f00d457e1.png)
 
![image](https://user-images.githubusercontent.com/4593242/35700619-c9f32b56-0793-11e8-82b6-7892ccdb3f59.png)

an other difference is greyframe starts displaying first data after a second and you cann see the scrollbar  getting smaller while more data is transfered

in authentic the screen stays empty until all data is transfered, this can take some time when thousends of packages are installed and all categries are open, im my case up to 20 seconds

**Comment by qooob** [comment]
Hi, Kay.

About displayimg things. Authentic can display things in progress if buffered header is used. (or the page itself is marked in the theme as progressive. Due to things loading using AJAX there is no way to display all pages the same old way. Which URL is the exactly you're talking about? Packages listing?

About navigation on page using #. Good point, I have never thought of it. I'll check tomorrow if it's possible to utilize.

**Comment by gnadelwartz** [comment]
its package tree: software/tree.cgi

**Comment by gnadelwartz** [comment]
I changed ` ui_print_header` to` ui_print_unbuffered_header`, but its not displayed progressive ...

**Comment by qooob** [comment]
Because theme part also needs to be tweaked.

**Comment by qooob** [comment]
New 19.09 version will support anchors for links.

Take a heed, Tree page doesn't deliver correct anchor names when there is space in the name. For example, System will open correctly, as the `#System` in URL correspond with the name in the link `name="System"`, while System Environment, will not work, because the URL is trimmed to `#SystemEnvironment`, while the name still uses the full name `name="System Environment"`.

Please fix this on the server side to make things fully work.

Kay, thank you for reporting.

**Comment by gnadelwartz** [comment]
I'll provide a patch for Jamie ...

**Comment by qooob** [comment]
Danke.

**Comment by gnadelwartz** [comment]
pls try if this may work https://github.com/gnadelwartz/webmin/commit/14c1107c42d468784c14cd166cbdfbe1899d83e5, can test it @home only

**Comment by qooob** [comment]
Okay, tried.

This also makes names to be printed together:

```

All Packages |  
-- | --
Applications |  
Development |  
SystemEnvironment |  
System |  
Unspecified |  
UserInterface


```

**Comment by gnadelwartz** [comment]
OK, I'll have a more deeper look home ...

**Comment by gnadelwartz** [comment]
This should fix it https://github.com/gnadelwartz/webmin/tree/ipkg
the problem was that close.cgi and open.cgi does not urlize the parameter ...

**Comment by qooob** [comment]
I have made a huge commit that also includes this issue fix.

Give it a try.

**Comment by qooob** [comment]
19.09 is out. Give it a try.

**Comment by gnadelwartz** [comment]
perfect!

**Comment by qooob** [comment]
I love this word!
