### ISSUE TITLE
Theme: Real-time monitoring gather optional metrics

### ISSUE THREAD

**Issue by WoozyG** [qooob/authentic-theme#1062]
I have a system with many bind mounts as part of user access management of centralized resources.  Webmin running the old default theme works just fine, no CPU use unless I'm actively doing something.  When running with this theme, however, the CPU spikes and stays at 100% apparently forever, or longer than my patience and cloud server CPU credits.

When the system has no bind mounts yet (after start-up, before app configuration) this theme behaves normally, but with an initial brief spike in CPU.  Once I add a few hundred bind mounts, all between points in the same physical file system, this theme's stats CGI starts to go crazy even when I'm not using webmin, and have all webmin background stats collection turned off.

**Comment by qooob** [comment]
You could also turn live-stats off in Theme Configuration/System Information page options section.

I suppose this is happening because you have to many mounts and theme's lie stat script is trying to query data from them and it takes forever. 

Right now you can disable them as mentioned before or you could edit `stats.cgi` under `authentic-theme` folder and comment out/delete lines from 57-68.

```Perl
  if (foreign_check("mount")) {
            foreign_require("mount");
            my @disk_space = mount::local_disk_space();

            $data{'disk'} = (@disk_space && $disk_space[0] && $disk_space[0] > 0 ?
                               [int(($disk_space[0] - $disk_space[1]) / $disk_space[0] * 100),
                                text('body_used_and_free',      nice_size($disk_space[0]),
                                     nice_size($disk_space[1]), nice_size($disk_space[0] - $disk_space[1])
                                )
                               ] :
                               []);
        }
```

It will let live-stats work without putting to much load on your CPU.

In the future I will add an option to selectively  disable/enable stats for CPU/Disk and other.

**Comment by qooob** [comment]
Ref.: Todo #_4_ https://github.com/qooob/authentic-theme/issues/896

**Comment by rostovtsev** [comment]
It's been added with the latest commit. Sorry for taking ridiculously long time.
