### ISSUE TITLE
Virtualmin custom links fails to open

### ISSUE THREAD

**Issue by nodo50** [qooob/authentic-theme#130]
I have a minor issue with the new theme in Virtualmin Pro. My custom links doesn't open. I set all for open in a new windows, they are links for phpmyadmin, webmail, my ticket system... I tested on last versions of Firefox and Chrome in Mac OS X 10.9.5. I don't use any plugin for block popups.

When I click on a link the right frame reload and show the wheel spinning but it never ends. If I do a SHIFT + click it works and open the link in a new tab.

best regards,
Nodo50

PS: the new Authentic theme it is a great job, congratulations! Virtualmin certainly needed this.

**Comment by sabzo** [comment]
Hi All,
I'm experiencing same issue as well. My list of virtual servers in Virtualmin 4.1.2 aren't showing on the left navigation. I don't have the drop down menu of selecting from my virtual servers (while in root). None root users aren't able to access Virtualmin either.

**Comment by qooob** [comment]
@nodo50 I have fixed it. Thanks for reporting. It will be working in version 10.30. You will not be able to choose to open the target though, because it's against `same origin policy` to open outside links inside of an iframe. So, you will get what you need - new tab will be opened when you click on the link.

@sabzo It's impossible that root user doesn't have select for virtual servers, same for non-root users can't access Virtualmin. Please be kind posting video-screencast starting right from complete page reload. What browser are you using by the way? If you still have a problem with it, please open new issue.

**Comment by sabzo** [comment]
@nodo50 Slight overlook on my part. After upgrading to version 4.15 it was all resolved. Much appreciation.

**Comment by qooob** [comment]
@sabzo You're welcome!
