### ISSUE TITLE
Loading dialog stays after Perl modules were installed

### ISSUE THREAD

**Issue by Rvanlaak** [qooob/authentic-theme#135]
After changing to this theme, we did also get the `Can't locate LWP/Simple.pm` error. So we've updated the server using `perl -MCPAN -e 'install Bundle::LWP'`

After refreshing the page, the only thing we see is the loading animated gif. Any clue on where we can look to find some extra errors? Do we need to install extra Perl packages?

**Comment by qooob** [comment]
Yes, because the the has some dependencies. In couple of days I will release the new version that will have NO dependencies and work out of the box. Make sure to install `LWP::Simple, either LWP::Protocol::https or Bundle::LWP, version, Net::SSLeay modules installed`. Also double click on the loader to dismiss it and see the error message. It's all in README.md actually.

**Comment by Rvanlaak** [comment]
Installing `LWP::Simple` via `cpan` did indeed solve it. To me it looked like installing `Bundle::LWP` did also include the first one mentioned :+1: 

I'm busy translating to Dutch, you'll see a PR within the hour

**Comment by qooob** [comment]
Thanks a lot! I will add it to the next release. ;)
