### ISSUE TITLE
Constant loading screen

### ISSUE THREAD

**Issue by jamesbaber** [qooob/authentic-theme#142]
After enabling this theme in the latest version of webmin all I see is a loading circle in the middle of my page. This has completely locked me out of what is otherwise a perfectly working webmin server.

**Comment by qooob** [comment]
:)

It's because some Perl modules are missing. Version 11.00 is coming very soon to completely fix this problem and bring new features. Meanwhile double click on the loader to make disappear and see the error message. There were familiar post just few days ago, it will help you to fix it. Please take a look:

#135

It's all on the README.md!

**Comment by jamesbaber** [comment]
Ah sorry, I assumed that it would be a less known issue as this is now included in webmin as default.
