### ISSUE TITLE
Feature request for upcoming Authentic Theme 17.20

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#293]
Do you have something to propose or have missing features? Please post it here with revealing details!

**Comment by fagner2010** [comment]
Hi, Theme not supported language PT-BR-UTF8?

**Comment by qooob** [comment]
No, not yet! Please use [English Template](https://github.com/qooob/authentic-theme/blob/master/lang/en.UTF-8) to translate it.

Afterwards, I will add you to the list of translators on the first page.

**Comment by fagner2010** [comment]
Thank you, and congratulations on the great work.

**Comment by qooob** [comment]
Thank you. :) When (If) you finish translations post a pull request or open new issue. I will have to delete these messages as it's not related with the title (features request).

**Comment by qooob** [comment]
Actually there is PT language. https://github.com/qooob/authentic-theme/blob/master/lang/pt.UTF-8

**Comment by qooob** [comment]
It's probably better to use this one as template. They are not the same?

**Comment by 7starsone** [comment]
yes, that's mine lol the first part... then you added some strings and so are in english...
there is just one error in that part (i guess).. "right_slcheck=erifique novamente licença Cloudmin" IS right_slcheck=***V***erifique novamente licença Cloudmin ;-)

**Comment by qooob** [comment]
I will take a look. Feel free to add translations to the missing lines! ;)

**Comment by qooob** [comment]
Scheduled in _Authentic Theme_ 17.20 release:

__To do:__
1. Using arrows up/down to navigate through history of executed shell commands in autocomplete search box
2. Extended notification drawer on the right (content) page
3. Add ticking time to the _System Information_ page
4. Add autoscroll feature support new upcoming  _Webmin_ version, for other pages of _Virtualmin/Cloudmin_ https://github.com/qooob/authentic-theme/issues/287
5. Update to the latest dependencies (Bootstrap/CodeMirror and others)
4. Fix small unnoticed bugs

__Maybe now, maybe next time, maybe later in the future:__
1. Add _Filemin_ desktop like tabs (Medium task)
2. Connect all _Webmin_ users into a group-chat using XMPP (will require manual enabling). The registration is planned to be made manually based on the provided credentials. (Hard task)
3. Change the way Mail works. Usermin should have _GMail_ like mail interface. Will be done as mine separate module or will require major change to the current _Webmin/Usermin_ `mailboxes/mailbox` modules. (Super hard task)
4. Add full support of XHR (background calls) to _Webmin/Virtualmin/Cloudmin_. The idea is just to make/apply changes, without constant page reload. Probably, will require to incorporate some hooks to WM/UM/VM/CM from Jamie and Joe. (Hard task)

Please feel free to comment or propose any other missing features from your point of view!

**Comment by idiotsavant** [comment]
I would love to be able to edit the left navigation menu. I use Webmin as a lightweight web GUI to launch shell scripts on a VM, for software testing. I have cloned and renamed the "Custom Commands" module many times, and I only use a few of the other standard modules regularly.

I have divided my modules into categories but I can't control the display order of the categories or the order of the modules within them in the left menu. In the standard Webmin themes the order of modules is controlled by the "desc=" field in the module.info file (alphabetical), but this has no effect in Authentic.

I also have three other web applications running on this server, and I would like to be able to have links to them in the navigation menu, so I could easily open them in a new browser tab directly from within Webmin. The same feature would allow for links to external resources, e.g. documentation hosted on an external site. I can achieve this by adding my links directly into authentic-lib.cgi but it's ugly and of course breaks during upgrades.

Many thanks for your work on Authentic!

**Comment by qooob** [comment]
You are welcome! 

In case the links inside of the categories are sorted alphabetically would that be good enough? It's done by _Webmin_ and the theme doesn't do much of anything there! I would request such functionality to _Webmin_ repo. However I could do it.. but not sure yet..

For the custom links, as far as I'm aware, there is _Webmin_ module for that! Virtualmin has it for sure - you could export it from there for your own use! On the theme side, you can manually edit `favorites.json` (making sure that you keep _valid_ syntax -  otherwise, unrecoverable, fatal error happens). In that file you could add custom links there - it that good enough?

Would that be useful to have ability to inject custom code into `authentic-lib.cgi` that would survive updates?

**Comment by qooob** [comment]
Yeah, the module is it's called `Custom Link`.

**Comment by idiotsavant** [comment]
Thank you for the "Custom Link" suggestion. It works with a single instance of that module, but if I clone the module it no longer works in the clones. If the "open immediately" option is selected in the module options nothing happens when you click the menu entry. I will ask the module author is that can be fixed.

Default modules are sorted alphabetically, but if you clone a module and rename a module, either using the "Module Titles" option in Webmin configuration, or by editing module.info then it isn't sorted by the new name. It's as if Webmin is still sorting by the underlying name, "Custom Commands" for example.

I can see how the Favourites option is useful, but it doesn't fit what I'm trying to do, which is present users with a simple left navigation menu that only contains options relevant to them. They don't even know what Webmin is, so I'm hiding almost all default modules from them.

Preserving the code during upgrades would be nice, but I don't think it is worth spending your time on: it's a very niche use case.

The reason I am interested in these features is that I see Webmin as more than a sysadmin tool: if you have a complex set of tools (in this case a whole suite of software testing apps, all capable of being controlled from the terminal) then Webmin is the best web based GUI for launching bash scripts I have found. The GUI means the tools can be operated safely by less technical users, and some of the default modules are a bonus (e.g. to monitor resources).

As I'm building a GUI for a set of apps rather than managing a server, I'm more interested in the interface, which is why Authentic immediately appealed, because its interface is so much better than anything Webmin had before.

Thanks again! Hope this gives you some ideas for the future.

**Comment by specktator** [comment]
Another enhancement I'm thinking is to have notifications about other servers status using VM's system status module to figure out warning levels, notification messages, update interval etc. 
It's going to be a hard task but I think it worth it.

+++ for:
> 2. Connect all Webmin users into a group-chat using XMPP (will require manual enabling). The registration is planned to be made manually based on the provided credentials. (Hard task)

> 3. Change the way Mail works. Usermin should have GMail like mail interface. Will be done as mine separate module or will require major change to the current Webmin/Usermin mailboxes/mailbox modules. (Super hard task)

I will help you for that!

**Comment by qooob** [comment]
>  ... would love to be able to edit the left navigation menu. 

Will be ported to the future todos.

**Comment by qooob** [comment]
>  ... would love to be able to edit the left navigation menu.  (from #293)

Will be ported to the future todos.

> ... to have notifications about other servers status using System and status module (from #293)

Will be ported to the future todos.

> ... you make an email HTML mock up of how you'd want it to look/work (from group chat)

Will be provided as promised in the future.

All other features will be ported to the new issue. Stay tuned.
