### ISSUE TITLE
Mobile view and full-screen browsing

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#294]
Hi, is possible to do something, to work in Full-screen browsing using the latest Firefox for Mobile?

I use the latest Firefox for Mobile and Galaxy S2, and my screen looks like this:

![screenshot_2015-12-06-15-13-08](https://cloud.githubusercontent.com/assets/7549566/11614026/00b89d30-9c2d-11e5-8c6a-97b343e5963e.png)

PS. other websites looks OK - The Firefox hides the bar when scrolling down a page.

**Comment by qooob** [comment]
I'm not really sure what I can do here?

**Comment by sz00gun** [comment]
The address tab should hide when you scroll down a website. Many website works with it but Virtualmin don't. This enhance browsing. Please have a look this option in FF

**Comment by qooob** [comment]
The reason why it's not working is because iframe is in use. Chrome also doesn't scroll it. If you open a page in Webmin with only right content, then it works fine.

I would guess, that it will not be possible to hide it. Bracase when you scroll the page, browsers think that you're not, as the top frame remains still. However, I will take a look.
