### ISSUE TITLE
Edit Users > View Passwords

### ISSUE THREAD

**Issue by simonbook** [qooob/authentic-theme#303]
The view passwords for users is no longer there.

**Comment by qooob** [comment]
Where exactly this is? In `Virtualmin->Edit Passwords`?

**Comment by simonbook** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/5818099/11919885/2b73e452-a7c3-11e5-8f42-d7f8c696c0eb.jpg)

**Comment by qooob** [comment]
Will take a look

**Comment by qooob** [comment]
It's not the theme issue. You need to enable plain-text passwords in Virtualmin. (off by default)

In order to make things work, on my test server I needed to create new virtual-server but before that I enabled plain-text passwords in `System settings->Server Template->Adminstration User->Store clear text passwords`. After that I could see the `Show` link (Version 17.21+ will have beautiful key icon for the password to show).

![screenshot from 2015-12-22 12-52-25](https://cloud.githubusercontent.com/assets/4426533/11952663/45a32a66-a8ab-11e5-8d2b-33e5b0d1680d.png)


> https://virtualmin.com/node/21042
