### ISSUE TITLE
A couple of cosmetic issues in the new notification function (Authentic theme version 17.20)

### ISSUE THREAD

**Issue by drkskwlkr** [qooob/authentic-theme#306]
![authentic](https://cloud.githubusercontent.com/assets/6951698/11941759/9b109220-a83a-11e5-811a-e39bc6107b71.jpg)
1 Message content
The message in the Notifications panel needs to be fixed:
```There are N package updates are available```
The second 'are' is unnecessary. Strangely, this behavior is not influenced when ```body_upneed=$1``` is redacted inside ```/usr/share/webmin/authentic-theme/lang/en.UTF-8```

2 "Hot" notification (red dot with number over the bell icon) will not clear itself after successfully performing update.

3 Language switching
The Notification panel will stay in English when interface language is changed via Webmin > Change Language & Theme

**Comment by qooob** [comment]
All recommendations are valid and will be fixed in 17.21. Thanks.

**Comment by qooob** [comment]
> 1 Message content

Will be fixed in 17.21.

> 2 "Hot" notification 

Notifications are not dependent on anything else. However, if you click on notification, it will be marked as read and will take you to the package updates (or other link, depending on the message).

> 3 Language switching

Language switching is hardcode for notifications and _FIlemin_ so far and will be fixed in future releases (17.22 - 17.30)
