### ISSUE TITLE
Selecting a VM from the drop down

### ISSUE THREAD

**Issue by SteffanCline** [qooob/authentic-theme#366]
I already mentioned on the closed issue that it's not fixed with the tap to open but aside form that, can you change the layout of the page that loads when you select the VM? It seems it should show a status of the VM, not an immediate edit page. You have to scroll down and expand that section. Seems logical for that to the the first thing you see.

**Comment by qooob** [comment]
Can you please attach a video-screencast or a screenshot at least.. I honestly have a hard time understanding what you mean about this issue.

**Comment by SteffanCline** [comment]
[tapping-closing.mov.zip](https://github.com/qooob/authentic-theme/files/111519/tapping-closing.mov.zip)

**Comment by SteffanCline** [comment]
Perhaps move "Detailed system status" to the top above "System details" although both are important. I can make a mock up of a possibly more user friendly appearance and see what you think.

**Comment by qooob** [comment]
Yes, I think I agree with you about moving Detailed System Status on top - makes sense.

I had to pull my MacBook Air out to try using Safari. You're using Safari, right? Well I must say to my surprise Safari really opens and immediately closes the drop down, but only if you click on the arrow. If you just click on the select itself - all is fine. I will try to fix this issue but I have no idea at the moment what is causing it - because it's only Safari.

Thanks for reporting.

**Comment by qooob** [comment]
..and after clicking for so many times on the arrow down, I could also reproduce it in Chrome! :D

**Comment by qooob** [comment]
I will fix select issue in 17.62 but fixing the order of the collapsible is up to Cloudmin developers. I shouldn't do and can't do it easily.

**Comment by qooob** [comment]
Please upgrade. The issue must be fixed now.

**Comment by SteffanCline** [comment]
No safari. Chrome on a MacBook Pro. I'll update and give it a shot. It felt like the issue might be where the hotspot was around the arrow.
