### ISSUE TITLE
NaN % in Virtual memory pie chart

### ISSUE THREAD

**Issue by selesta-rdhw** [qooob/authentic-theme#398]
I'm using Webmin 1.780 with Authentic theme 17.71 on an embedded system with no virtual memory. The very first time the interface is loaded after a succesfull login the 'virtual memory' pie chart is shown with NaN % (like it calculates div by 0).
Any refresh of the status page is correct with no virtual memory pie chart shown.
The line Virtual memory correctly indicates '0 bytes total/0 bytes used' in both cases.
![immagine 2](https://cloud.githubusercontent.com/assets/9549090/13138461/bd016db2-d627-11e5-8d81-d30385b594f5.png)

**Comment by qooob** [comment]
I'll take a look.

**Comment by Schnuecks** [comment]
Hello,
i temporarily created an swap file via fstab and it works.
Without the swapfile it shows NaN%
But if you could fix this, i could remove the swap dummy. Or you create a query that proofs the existense of swap etc. an if not disable the chart or so.

**Comment by qooob** [comment]
I can't even remotely imagine why when you get `NaN` on output, it's not hidden, when it should.

What happens if you go to line

`( ( $disk_percent || $disk_percent eq "0" ) ? $disk_percent : 'NaN' )`

and lets say replace it with

`( ( $disk_percent || $disk_percent eq "0" ) ? -sin(9**9**9) : 'NaN' )`

Will you have `Local Disk Space` chart hidden?

What browser are you using?

**Comment by qooob** [comment]
I could reproduce your bug. I will fix it in 17.72

**Comment by selesta-rdhw** [comment]
Thanks a lot Ilia!
Your job is really beautiful and your commitment deserve an applause....and a little donation too!!!

9M072990289196125

**Comment by qooob** [comment]
Thank you!

**Comment by qooob** [comment]
Please upgrade to 17.72.
