### ISSUE TITLE
Show page content while loading

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#440]
Hi,

There used to be a setting to disable the content spinner .. I like to be able to see what Virtualmin is doing .. eg. doing large backups etc .. Having the spinner there all the time hides what's happening ..

Has this setting been removed or moved? .. Can we have it back?

**Comment by qooob** [comment]
The page can be dismissed by double-clicking on it. (starting 18.80+).

Module exclusions can provide you with complete disabling rendering for specific modules, you could set `virtual-server` there but it's not recommended as VM fully supported.

For the backups you mentioned, next release will have spinner disappear when the backup process starts (I thought it was there already but it seemed that not).

Expect it to be fixed in 17.84.

**Comment by qooob** [comment]
17.84 is out. Please upgrade.

**Comment by neubreed** [comment]
Thank you ! :)
