### ISSUE TITLE
Usermin - Mail - Active Folder (class sub_active?)

### ISSUE THREAD

**Issue by cynetix** [qooob/authentic-theme#531]
Hi Qoob,

I am not sure if it's supposed to work or not, but when in Usermin and on the mail tab it defaults to "Inbox" and is in the active state, however if you select another directory, for instance "Sent" the active status isn't switched and remains on "Inbox".

When switching to say, "Address Book" it does switch, it's just the folders that don't work.

Is it a bug, or does the sub_active class just not switch on those li's?

**Comment by qooob** [comment]
Not sure exactly what you mean but I have just took a looked and things seem to work ok.

When you choose the _select_ that is preceded by _Move to:_ button, then yes it doesn't switch. When you do it at the very top, things change automatically. However, if it doesn't work, you can always click _change_ button to force the submit. In case you're using the keyboard while circling through select's options you need to hit enter to submit it.

I'm not performing any improvements on the mail, because I'm planning to release completely [new mail](https://github.com/qooob/authentic-theme/issues/431) UI in the near future. (my best plan by the New Year).

**Comment by cynetix** [comment]
Hi Qooob,

As far as I can tell I think it's a bug, as in something is broken not something that needs changing.

The problem is this:

If I am on the inbox I get this:

![inbox](https://cloud.githubusercontent.com/assets/20661756/17554648/ca11868a-5f03-11e6-8c71-01c2316295e3.PNG)

If I am on another folder I get this (in this example the sent folder):

![sent](https://cloud.githubusercontent.com/assets/20661756/17554671/dd7d4484-5f03-11e6-94da-a3fdf938014e.PNG)

Notice the folder selection on the left remains on inbox regardless of the folder selected, clicking change doesn't do anything.

If it is a bug, and you don't plan on fixing it, that's fine, but do you know where the problem lies so we can take a look ourselves?

**Comment by qooob** [comment]
Directly clicking on Send in the left menu will open the right content in the right frame?

**Comment by cynetix** [comment]
Qooob,

Yes, I think we may be talking at slightly cross purposes here.

The functionality appears fine, if you click any of the links the right panel responds correctly. It's just the left panel directory links aren't reflecting what is on the right screen. So the active status isn't updating.

Looking at it my brain tells me that if I am on the sent mail page, the sent mail option on the left should have the highlight. In other words it should have the coloured line next to it and opacity set to 1.
