### ISSUE TITLE
Webmin 1.830 required? Auto-update does nothing on 1.820

### ISSUE THREAD

**Issue by sbaker-gsc** [qooob/authentic-theme#603]
The requirements currently list Webmin 1.830 as required - yet this is not released - is that intentional or a typo? If intentional that might explain the problem below.

When trying the auto-update on Webmin 1.820 on Centos 7.2 from authentic 18.10 nothing happens. Installing manually from the downloaded archive seems to work fine. I had the same issue updating to 18.30 and I believe the intent was the 18.31 had fixed that - I just wanted to alert you to the fact that it's still an issue. 

Client is Chrome browser on Win10 
To reproduce just click the "update" button from the dashboard. The dashboard goes grey, the fillbar works about 3/4 of the way across and then I'm dropped back to the dashboard again with no change and still on the current theme.

Hope that helps - if you need more info let me know.

**Comment by qooob** [comment]
Hi,

Thanks. Yes, I set it 1.830 intentionally as requirement, because Jamie is going to release it soon. **SELinux** and **file attributes** support for File Manager will only work in Webmin 1.830+. 

It will install without issue but technically it requires Webmin 1.830+.

Auto-updates are back with 18.31 for both Webmin and Usermin. Unfortunately there is no back-compatibility for auto-updates with theme version <18.30.
