### ISSUE TITLE
File Manager: First load broken navigation actions

### ISSUE THREAD

**Issue by qooob** [qooob/authentic-theme#665]
After very first _File Manager_ load the navigation path dropdown and crumbs don't work correctly, resetting to the root path.

**Comment by brianforan** [comment]
Do you mean under 'others'? I was noticing this issue. My work around (other than searching for file manager) currently was to automatically route users to file manager or to their only available module, since it's likely they'll only have file manager anyway. Interested to see if you find a fix for this though.

**Comment by qooob** [comment]
I have no idea what are you talking about?

The issue I described happens on the first time a tab is instantiated. It's healed by clicking _reload_ button.

Do you have some other issue?

**Comment by brianforan** [comment]
No, this was my issue. It was happening a few times and when I went to replicate it was fine.
