### ISSUE TITLE
show when i'm running on a hot-fixed version

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#676]
I did as you told me, i cloned the repo but i can still see i'm running on `Authentic Theme 18.32`. I was wondering if you could show some kind of build version so i know what build (hot-fix) version i'm running?

**Comment by qooob** [comment]
Yes. You're absolutely right. After version 18.40 is released it will be possible, as it will have beta channel support.

**Comment by Sopor-** [comment]
I'm now running at a hotfix but the Dashboard will still show `Authentic Theme 18.40`.
I don't have beta channel enabled. I run a script that will update from git when new commits are made. Do i really need to enable beta channel for it to show hotfixes?

**Comment by qooob** [comment]
😂 I was sure that you would come back to it. I added beta chanels, yes. At the moment it might brake old users updates in case I start to put funky strings to the `VERSION.txt` file.

What you should do is to make sure that your script will patch 18.40 string to something else upon pulling.

Next beta will include the fix for it and make things fail proof for both Git and taged releases.

**Comment by qooob** [comment]
Give it a try.
