### ISSUE TITLE
Module links missing from menu

### ISSUE THREAD

**Issue by johamm** [qooob/authentic-theme#826]
I'm struggling to find out how to add links to the menu as it appears I'm missing quite a few modules from the navigation despite them being installed.

The main area I need to go to at the moment is System > Running Processes but I can't figure out how to get there.  You'll see from the screenshot what I can currently see under System (and also the CPU usage which is what I'm trying to investigate):

![image](https://user-images.githubusercontent.com/2692644/28666617-0d0e14a0-72c0-11e7-8555-cb1b428daf4e.png)

**Comment by qooob** [comment]
Hi,

It simply means that _ Running Processes_ module is not enabled in currents user configuration.

You just need to click on _root_ (near the logout button) and there check for the tab called `Available Webmin modules`. You will be able to see which modules are disabled and which are enabled.

Let me know if I can help you more.

Regards,
Ilia.

**Comment by johamm** [comment]
Thanks for coming back to me so quickly!

I've tried clicking on "root" but it's not actually a button for me... Not sure why!

**Comment by qooob** [comment]
It's because you as well have no access to _Webmin Users_ (ACL module).

Interesting.

Then you would need to manually edit `/etc/webmin/webmin.acl` file and add there at first _acl_ string.

The file should look like:

```Bash
root: backup-config webmincron usermin webminlog webmin acl ...
```

Make sure to add `acl` at the end. Save the file and restart Webmin by running

```Bash
/etc/webmin/restart
```

After doing above you will be able to have visual control over the modules in _Available Webmin modules_ under _Webmin/Webmin Users/root_.

**Comment by johamm** [comment]
Genius! Thank you for that, much appreciated :)

**Comment by qooob** [comment]
You're very welcome. Glad to help. 

Let me know if you have further questions.
