### ISSUE TITLE
Timezome change from 12h to 24h

### ISSUE THREAD

**Issue by theAnDrO40** [qooob/authentic-theme#855]
On the Dashboard i want to Change the time and Date Format to 24h i changed the Language in Webmin configuration from utf8 en_us to en_gb utf8 but nothing Happens date and Time format are displayed 12h am pm format

**Comment by qooob** [comment]
Date and time for System Information page are controlled using theme's settings. Try settings `LLLL` for long format.

**Comment by Abasz** [comment]
I think this is due to the fact that in authentic-init.pm the get_current_user_language sub subtracts the "_gb" part of the language name (as only two characters from the beginning is allowed the html data-language tag gets only "en". Which is interpreted as US time format by the momentjs.

A logic may needed to be introduced that checks whether the language is 2 or 5 character long (i.e. "en" or "en_GB") or if the string before the ".utf-8" is returned by get_current_user_language.

sub get_current_user_language
{
    return
      substr(
             ($gconfig{ 'lang' . '_' . $base_remote_user } ? $gconfig{ 'lang' . '_' . $base_remote_user } :
                $gconfig{'lang'}
             ),
             **_0, **_2_**);_**
}

I am not very good at Perl but somthing like a regex check could work. The below is probably not a very elegant way but it works :)

$lang_string = ($gconfig{ 'lang' . '_' . $base_remote_user } ? $gconfig{ 'lang' . '_' . $base_remote_user } :
                $gconfig{'lang'});
$lang_string =~ s/\..*//;
return $lang_string

**Comment by theAnDrO40** [comment]
Sounds very good but i am Not The best in edit files like this where should i paste this code

**Comment by theAnDrO40** [comment]
Sorry @qooob LLLL is Standard Setting ist does Not work

**Comment by qooob** [comment]
I will push the commit tomorrow morning, so you could test it. It should just work. No need to edit theme's settings. After installing tomorrow's patch it will just show up correctly.

**Comment by qooob** [comment]
**Unsent from yesterday:**
_momentjs_ accepts full string in `locale` function, thus `en-gb` will work just fine.

Thank you for pointing this out.

I'm adding this for 19.01 release that is scheduled for tomorrow. :wink:

**Comment by qooob** [comment]
Give it a try, please.
