### ISSUE TITLE
Theme information/changelog opens outside of viewable page

### ISSUE THREAD

**Issue by tgp1994** [qooob/authentic-theme#858]
* What is your server-side OS and its version?
**Debian 9, Webmin 1.860, Authentic Theme 18.49-9**
* What is your client-side OS, browser and its versions?
**Windows 10, Firefox 56.0.1 (64-bit)**
* What are the steps to reproduce the issue?
1. Open Webmin dashboard
2. Under the Theme version row, click on the "i" icon

When I view the Theme information (updates), the box appears to open up above the rest of page, when it should be several hundred pixels lower.

![webminthemeinfobug](https://user-images.githubusercontent.com/842942/31577973-cbca56e8-b0cc-11e7-8350-cc0493e3313f.png)

(In this picture, I was already scrolled to the top of the page.)

**Comment by qooob** [comment]
It's alright. 18 branch is no longer supported.

Please got to theme's settings and force update to latest development version, which is becoming release of 19.01 around tomorrow.

19.xx has this issue fixed.

**Comment by tgp1994** [comment]
@qooob I'm not sure I entirely understand, this is the default theme provided by a default Webmin installation. Will I (and every other user) be automatically updated? I didn't see this bug being reported before so I assumed it was unknown.

**Comment by qooob** [comment]
In some time, maybe around a month or even sooner, we'll enroll version 19.00 to Webmin package.

This [issue has been reported](https://github.com/qooob/authentic-theme/issues/786) and only appears in Firefox due to iframe.

Right now, you can upgrade it manually. After upgrade you could also enable in theme settings to notify about new theme's updates (at the bottom of the page). Version 19.00 is very stable right now. 

No worries at all.

If you have further questions I'd be glad to help.
