### ISSUE TITLE
File Manager: upload error

### ISSUE THREAD

**Issue by Abasz** [qooob/authentic-theme#868]
Hi, When I try to upload a file in the File Manager, a new window is opened but an error is displayed:

**Not Found
The requested URL /uptracker.cgi was not found on this server. 

Apache/2.4.18 (Ubuntu) Server at 192.168.1.2 port 443**

Nevertheless, the file uploads properly so this may not be a big issue

I use proxypass in apache (I access webmin via https://IPAddress/webmin/
	ProxyPass /webmin/ https://localhost:10000/
	ProxyPassReverse /webmin/ https://localhost:10000/

**Comment by qooob** [comment]
It only file-uploads properly for non-proxy configuration, thus yours should fail.

It's due to the bug in File Manager. I've made a patches for it. (https://github.com/webmin/webmin/pull/668, https://github.com/webmin/webmin/pull/669)

Besides, we are only few weeks away from replacing all file uploads (for Upload and Download module, as well as File Manager and Mail) to nice [JQ file upload](https://blueimp.github.io/jQuery-File-Upload/) (supporting multiple uploads).

I will not be fixing it right now more thoroughly.

**Comment by Abasz** [comment]
Thanks for the update, its not a big problem right now. looking forward for the new modules
