### ISSUE TITLE
Buttons not working authentic 18.49-9

### ISSUE THREAD

**Issue by divyeshsachan** [qooob/authentic-theme#899]
Hi, 

None of the buttons on any page are working, after recent firefox update (57.0).

Console logs error [Error: Permission denied to access property "apply"] link https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Property_access_denied?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

Even tried upgrading authentic to 19.xx in new window but still not working. Could be iframe property issue. 

![image1](https://preview.ibb.co/mQ6yJR/Untitled.png)
![image2](https://preview.ibb.co/bUMb56/Untitled0.png)

**Comment by divyeshsachan** [comment]
Just checked in another server, problem also exist in authentic version 19.02

**Comment by qooob** [comment]
Hi,

It's [known](https://github.com/angular/zone.js/issues/489) issue in different cases and with different applications.

I tested it with Firefox 57-59a - all works correctly. I suspect that it's happening because of dated extensions in your Firefox browser.

Try disabling extensions or simply try in incognito mode (tab). You will not have this error from happening.

**Comment by qooob** [comment]
Firefox 57 is very big update it has lot's of changes.

I would also recommend to trash all cache and start Firefox anew.

**Comment by divyeshsachan** [comment]
Hi, You were right. I restarted firefox in safe mode and everything worked perfectly.
Again i rechecked by disabling my addons one by one and found the culprit.
The issue was due to the addon "Free Download Manager".

Thanks for pointing to the right direction. :-)

**Comment by geotekberlin** [comment]
Same effect here with Shorewall Module: Buttons are not working with Firefox 57.0.4 and previous versions. Clearing cache, deactivation all Firefox plugins and running in safe mode does **not** help. This bug is repeatable with different computers but it seems only the buttons in Shorewall are affected. Going back to Gray Framed Theme makes them work again. So please re-open this issue!

**Comment by qooob** [comment]
This issue had to be fixed on the Webmin side a while ago.

I'll double check.

Which Webmin version do you run?

**Comment by geotekberlin** [comment]
I am using Webmin 1.8.70

**Comment by qooob** [comment]
@geotekberlin This has been fixed in Webmin's module.
https://github.com/webmin/webmin/commit/bad3e5272feefd50989442fc77a983592526ddd2
