### ISSUE TITLE
Recent Logins

### ISSUE THREAD

**Issue by JimTR** [qooob/authentic-theme#909]
The recent logins information from sysinfo.cgi is sometimes incorrect
To reproduce 
1. login to the CP and tick remember me
2. close the browser and change your ip to connect to the CP
3. relogin to the CP --- at this point you are not asked for a user name & password
from this the recent logins section shows you as logged in (correct) but shows the IP of when you hit the 'remember me' option and not your actual IP .. perhaps there should be a function to clean all obsolete logins and update the current one ?

**Comment by qooob** [comment]
Hi, Jim.

You can already view and disconnect current login session by going to _Webmin/Webmin Users/View Login Sessions_.

I would also recommend to bind session to an IP address, meaning when you login from another IP the session will not be valid. You can do it by going to _Webmin/Webmin Configuration/Authentication_ and there tick `Limit sessions to the same client IP address`.

I doubt that Jamie when planning _WebminCore_ missed the subject point. It seems to be made on purpose that session reflects the initial IP but not the recent one. In case you think otherwise, please file an issue to [Webmin repo](https://github.com/webmin/webmin/).
