### ISSUE TITLE
Panorama General now opens in a separate TAB, why?

### ISSUE THREAD

**Issue by matrix200** [qooob/authentic-theme#924]
Server side: Centos 6.9 
Client side: Windows 7x64, Palemoon 27.6.2 (32bit).
Steps:
Attempt to access: panorama general in webminstats plugin.
Also it appears it is no longer possible to bookmark it, the previously create bookmark didn't work and the bookmark icon is missing from the view.

**Comment by qooob** [comment]
Panorama General, in case not opened in new tab takes a very long time to load. 

The script itself is keeping connection for exactly 60 seconds.

I don't know what reasons are behind it. 

**Webminstats module needs a fix due to Webmin switching to new level of UI/UX using AJAX calls for everything.**

In case module has progressive output, it should use internally buffered header function.

_I'm dropping all code references to Webminstats letting developer **upgrade the modules's code** and make it just work right._ Besides, most of the time, the reason why things don't work, is because of non-complient  application of Webmin UI library. HTML on the output should be valid, as it's run through the parser and in case of the broken response, things might not work as well. For example, if there is no closing `</body>` tag, it will fail to work.

In case this module is popular, I'd recommend contacting developer of this module, asking to improve its UI and test it in the latest Webmin release. I would also update very dated icons and fixed other issues.

It's up to the module's developer to decide. I will not provide patches for something that should be fixed in third-party modules. There are most (almost all of them) of Webmin core modules that just work out of the box and need no sorcery. Just learn from it. I would recommend _Fail2Ban_ module to learn from. Everything just works and looks fantastic just by using Webmin UI lib.

The only exception that I make is for _ConfigServer Security Firewall_ module but I don't fix there much of anything, I just make it look like it should in Webmin.

**Comment by bcutter** [comment]
So... there will be no fix in authentic theme for that issue? I found this and I´ve no idea which side will fix it:
https://sourceforge.net/p/webminstats/bugs/97/

**Comment by qooob** [comment]
It's difficult to say. I could take another look a bit later, but I believe mudule's developer should take care of it.

**Comment by bcutter** [comment]
That would be great, just do be sure. Some users heavily rely on both software pieces (webminstats, especially panorama view - and the beautiful authentic theme) and suffer for months. So any small update/progress is great :-)

**Comment by gerbier** [comment]
The problem was coming from a process fork. It is fixed in a new beta release, and will be fixed in next release (2.18), coming soon

**Comment by qooob** [comment]
Great news, thanks!
