### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by mkkeck** [qooob/authentic-theme#93]
Hi,
I'm missing some icons form the Gray-Theme in the right-handed box.
Because listing the module names without any icon makes usability difficult. Is it possible to attach some of these or some new icons?

**Comment by qooob** [comment]
Hi! Well this is most questionable issue. Everytime, I switch back to old theme to check on something, I get disturbed with that icons that practically doesn't make much sense at all and it eventually takes much more time to find needed link. When it's a list of links close to each other - it's easier for an eye to read this kind of text. When it's icons with links - then you more get used to icons position rather than using link's text itself.

Version 9 of the theme provides Autocomplete even for right-handed box. For example, when you go to `Webmin Configuration` module, all links from the right box are in Autocomplete and searchable - which means you don't even have to look at right side anymore to find desired link.

I think having icons on the right side is kinda vestiges of the past. We all got used to it but eventually realize that it's even better without it.

My answer is no, I will not be able to invest my time into something like that, at least at the moment. We will get back to this discussion with Joe by the time Webmin 2 will be ready for production, which is months away from now.
