### ISSUE TITLE
usermin after latest upgrade

### ISSUE THREAD

**Issue by xinomilo** [qooob/authentic-theme#936]
After latest webmin upgrade (1.870), usermin (1.720) no longer works with authentic theme(19.04). only left side column shows up, but is unresponsive. and nothing shows on the right.
![usermin](https://user-images.githubusercontent.com/2060376/33825083-2462b704-de69-11e7-956d-ff2254564f28.png)
using any other usermin theme, and everything works as expected.

* What is your server-side OS and its version?
Latest Debian stable.
* What is your client-side OS, browser and its versions?
Debian, Firefox 57.0.1, Chromium 63
* What are the steps to reproduce the issue?
upgrade to latest webmin and login to usermin.

**Comment by qooob** [comment]
Hi,

Theme works both fine in Webmin and Usermin as well. 

From your screenshot I can see that you have strange URL entered there. Make sure to clear browser's cache and set URL ending with `.....20000/`.

In case it still doesn't help, go to theme's settings in Webmin and run force-upgrade from development channel.

**Comment by qooob** [comment]
Yes,

I tried all your steps above on Ubuntu installation.

It's also worth trying restarting Webmin and Usermin from console.

**Comment by superlgn** [comment]
Sorry to comment on a closed bug but I believe I'm experiencing this as well...

At first I thought I just needed to restart usermin after some type of incompatible change came along with the webmin update last week, but another report came in today. If I restart usermin and login directly to usermin it's fine, but when I use the 'Login to usermin' button in the webmin user editor then suddenly usermin is broken and looks like the screenshot above. It's not just this admin session either, but any new or existing sessions. Reloading the direct login shows the breakage as well and the only way to fix it is to restart usermin.

Nothing stands out in the miniserv.error log. The only difference is when things are working properly there's a whole lot more warnings.

We had a similar problem a few months ago that was fixed by manually upgrading the authentic theme or receiving it with the webmin update that came out a few days later.

Forcing a theme update from stable appears to have fixed this problem, although the Authentic version number itself didn't change. It's still 19.04. Not sure if that forced update may have cleared out some bad cache or what.

Thanks,

Mike

**Comment by qooob** [comment]
Hi,

You could try few things.

At first, upgrade Usermin to 1.730.

Second try to upgrading the theme using Force Update option in theme's settings.

As last clear browser's cache and/or try incognito window.

I just tried it over again and it just worked for me.
