### ISSUE TITLE
Problems with Portuguese UTF-8

### ISSUE THREAD

**Issue by fernandolcardoso** [qooob/authentic-theme#950]
**In (default) English**
![image](https://user-images.githubusercontent.com/16019127/34114937-45dfdfa0-e3fb-11e7-8f30-478bc5316bab.png)

**In Auto Detection to Portuguese BR**
![image](https://user-images.githubusercontent.com/16019127/34114554-3d09d10c-e3fa-11e7-8ad4-0602599717b3.png)

![image](https://user-images.githubusercontent.com/16019127/34114850-035fcd98-e3fb-11e7-89a3-5a179bf9ce65.png)

**Comment by gnadelwartz** [comment]
does this also occur if you manually set the language to Portuguese utf-8

**Comment by fernandolcardoso** [comment]
When I force myself to use the Brazilian language, there are other problems:

![image](https://user-images.githubusercontent.com/16019127/34114989-6963c93c-e3fb-11e7-94bc-a8480295b68c.png)

![image](https://user-images.githubusercontent.com/16019127/34115045-92a040be-e3fb-11e7-9e0a-bb38268110ad.png)

![image](https://user-images.githubusercontent.com/16019127/34115096-bd692cca-e3fb-11e7-8d2d-33f6adfc8606.png)

![image](https://user-images.githubusercontent.com/16019127/34115116-ca8cade6-e3fb-11e7-90e9-bd6c6464c40a.png)

**Comment by gnadelwartz** [comment]
i checked translations for two cases where you have problems, in bith no brasilian translations are availible for webmin. it seems the Portuguese one is used instead. e.g. server index.

**Comment by gnadelwartz** [comment]
so it seems not an authentic theme issue.

@qooob any other opinions?

**Comment by qooob** [comment]
Hi,

This problem originates from commits to Webmin repo, where commiter messed up with the file encoding.

Looking at _[fdisk/module.info](https://github.com/webmin/webmin/commits/master/fdisk/module.info)_, you could see where exactly it went broken. At the moment the encoding is set to `western-8859-15`, while changing it to `UTF-8` fixes the issue (partly).

In case you want explicitly set the string for _pt_BR_, you would have to go with:

```
desc_pt_BR.UTF-8=Partições em Discos Locais
```

After editing this file, in order to have changes displayed, you need to _Refresh Modules_.

This is not the theme issue. All of those files much be saved in _UTF-8_ encoding.

It's important not to break it. There are many files like that. People seem no to pay attention when submitting translations.

Please be patient and kind to submit this as an issue to [Webmin repo](https://github.com/webmin/webmin/issues/).
