### ISSUE TITLE
Update to v19.06+ breaks the Webmin UI

### ISSUE THREAD

**Issue by laukstein** [qooob/authentic-theme#967]
Webmin shows:

![grabilla q11140](https://user-images.githubusercontent.com/183966/34423463-dc172bdc-ec24-11e7-86e0-6703fc99a072.png)

When clicking theme Update, it breaks the Webmin UI and shows:

![grabilla uh2108](https://user-images.githubusercontent.com/183966/34423482-fb165828-ec24-11e7-9893-0272ba00cca6.png)
---
After trying theme install manually, v19.06 and v19.07 shows warning "Module authentic-theme requires Webmin version 1.871 or above" and with v19.05 it seems working fine.
**Notice** that [Webmin](https://github.com/webmin/webmin/releases) current latest version is 1.870. 

Perhaps the Update button needs to check if Webmin version is compatible for the version and even better to not show Update button if not compatible, to avoid confusion and potentional running into issue.

**Comment by qooob** [comment]
It shouldn't break anything. It looks exactly as cache issue and all you need to do is to hard reload the page. I run it on the production server with 1.870 Webmin.

I always tend to make it cross compatible. Usually it means that something might not work correctly, for example history in inbuilt command shell in this particular release.

However, I like your idea, it's worth doing it, and logically correct.

**Comment by laukstein** [comment]
@qooob here is what I get when trying to update v19.06 and v19.07

![grabilla uh2736](https://user-images.githubusercontent.com/183966/34425277-508ae9a0-ec33-11e7-8177-5caf8b1a43ed.png)

and clean-cache, neither Webmin restart would solve the broken Webmin issue after "Update". When I checked the HTML, it was missing CSS and JS files.

**Comment by swelljoe** [comment]
This may be another variation on the theme of "Webmin didn't actually restart". For some reason that I don't think any of us have figured out yet, Webmin/Usermin no longer restart properly in some circumstances on systemd systems. Forcing it to restart (manually killing the process and then restarting it with `systemctl restart webmin`) will likely fix it. 

There's a whole lot of ways this can manifest depending on what's changed in the theme since the last restart, but given how many problem reports we've had in the past few days that are due to Webmin not actually being restarted, I'm pretty confident that's what's happening here, too.

**Comment by qooob** [comment]
@laukstein  The message that you get is expected and intentional. Installing a package, has to work out of the box. This is the warning, that tells you that this theme package, really depends on unreleased version of Webmin (development). In case you update to development version using theme update, then you'd be aware that it's development version.

Webmin has a script `update-from-repo.sh` to update to the latest version. Theme has `update-theme.sh` to update to ether stable or development version. Try running it with `--help` switch to get more details.

In case you still that stuck screen, try:

```
pkill -9 miniserv
```

and then restart both Webmin and Usermin:


```
service webmin restart
```

```
service usermin restart
```

**Comment by laukstein** [comment]
@qooob please ReOpen this issue and fix it.
@swelljoe no restart would solve it.
Authentic Theme mustn't ask to update to incompatible version that would break all the interface, in first place.
At least Authentic Theme stable version must match the stable latest version of Webmin - authentic-theme stable compatible for webmin stable, authentic-theme development for webmin development. Do you understand what I mean?

**Comment by qooob** [comment]
I did understand what you meant and even I added your request into local to-do list. I will make it more precise with next release, no worries here.

About fixing.. there is nothing I can fix really.

Like I said, try updating the theme or Webmin completely or try to kill the process and restart it. I hope you tried to hard reload browsers cache and/or clear cache completely.

I have 19.07 running with 1.870 just fine.

**Comment by laukstein** [comment]
@qooob and what happens when you try to install manually, does it show requires Webmin v1.871?

**Comment by qooob** [comment]
Yes, of course. This package is not 100% compatible, and this message is indication of it.

Okay, I've repacked the package to avoid future questions.

**Comment by qooob** [comment]
I have added a check based on `theme.info` and `depends=` key to check on development versions dependencies.

In case development theme version requires unreleased version of Webmin/Usermin, the user will be notified.


![screenshot from 2018-01-24 12-20-18](https://user-images.githubusercontent.com/4426533/35326185-f3a37c3c-0106-11e8-8823-d6c1eae944c0.png)

https://github.com/qooob/authentic-theme/issues/966#issuecomment-360080848
